version: '3.8'

services:
  db:
    image: postgres:15
    container_name: marketplace_db
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: marketplace_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: marketplace
      DB_PASSWORD: secret
      DB_NAME: marketplace
    volumes:
      - .:/app
    command: ["./marketplace"]

volumes:
  db_data: