services:
  marketplace_postgres:
    image: postgres:15
    container_name: marketplace_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shared-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  marketplace_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketplace_app
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      marketplace_postgres:
        condition: service_healthy
    ports:
      - "${PORT:-8080}:8080"
    networks:
      - shared-network
    volumes:
      - ./.env:/app/.env

volumes:
  pgdata:

networks:
  shared-network:
    external: true